//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouchard
    {
        public int id { get; set; }
        public Nullable<int> idStagiaire { get; set; }
        public Nullable<System.DateTime> DateInscription { get; set; }
        public string Qui { get; set; }
    }
}
