//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaires
    {
        public long IdStagiaire { get; set; }
        public string NomStagiaire { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string CP { get; set; }
        public string Pays { get; set; }
        public string Pseudo { get; set; }
        public Nullable<byte> Age { get; set; }
        public Nullable<byte> Specialite { get; set; }
    
        public virtual Specialite Specialite1 { get; set; }
    }
}
